pointcloud_to_laserscan:
  ros__parameters:
    range_max: 10.0
    use_inf: false
    target_frame: "base_link"
    max_height: 10.0
    angle_min: -2.356194490192345
    angle_max: 2.356194490192345
    angle_increment: 0.004363323 # 4 points per degree